const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('easyarc', {
  hidTest: () => ipcRenderer.invoke('bridge:hidTest'),
  hidProbe: (targets, durationMs) => ipcRenderer.invoke('bridge:hidProbe', targets, durationMs),
  hidDetectPress: (targets, durationMs, threshold, excludeSerials) => ipcRenderer.invoke('bridge:hidDetectPress', targets, durationMs, threshold, excludeSerials),
  matchHidControllers: (targets) => ipcRenderer.invoke('bridge:matchHidControllers', targets),
  matchHidByPath: (path) => ipcRenderer.invoke('bridge:matchHidByPath', path),
  matchHidBySerial: (serial) => ipcRenderer.invoke('bridge:matchHidBySerial', serial),
  findRetroArch: () => ipcRenderer.invoke('bridge:findRetroArch'),
  findDolphin:   () => ipcRenderer.invoke('bridge:findDolphin'),
  launchPPSSPP:  (romPath) => ipcRenderer.invoke('bridge:launchPPSSPP', romPath),
  // RMG_SLICE1_2026-06-20: N64 via RMG (download/extract + launch; no controllers yet).
  ensureRMGReady: () => ipcRenderer.invoke('bridge:ensureRMGReady'),
  launchRMG:      (romPath, controllers) => ipcRenderer.invoke('bridge:launchRMG', romPath, controllers),
  // FIX_2026-06-19_PSP_LIFECYCLE: game-running lifecycle events from main process.
  onGameStarted: (callback) => ipcRenderer.on('game-started', () => callback()),
  onGameExited:  (callback) => ipcRenderer.on('game-exited',  () => callback()),
  findDuckStation: () => ipcRenderer.invoke('bridge:findDuckStation'),
  installDuckStation: () => ipcRenderer.invoke('bridge:installDuckStation'),
  scanForPSXBios: () => ipcRenderer.invoke('bridge:scanForPSXBios'),
  configureDuckStationBios: (biosDir) => ipcRenderer.invoke('bridge:configureDuckStationBios', biosDir),
  browseForBiosFolder: () => ipcRenderer.invoke('bridge:browseForBiosFolder'),
  onDuckStationDownloadProgress: (callback) => ipcRenderer.on('duckstation:downloadProgress', (_e, data) => callback(data)),
  offDuckStationDownloadProgress: (callback) => ipcRenderer.removeListener('duckstation:downloadProgress', callback),
  getConfig: () => ipcRenderer.invoke('bridge:getConfig'),
  setConfig: (values) => ipcRenderer.invoke('bridge:setConfig', values),
  listCores: () => ipcRenderer.invoke('bridge:listCores'),
  coreExists: (system) => ipcRenderer.invoke('bridge:coreExists', system),
  installCore: (system) => ipcRenderer.invoke('bridge:installCore', system),
  pickRomFolder:    () => ipcRenderer.invoke('bridge:pickRomFolder'),
  pickParentFolder: (folderName) => ipcRenderer.invoke('bridge:pickParentFolder', folderName),
  scanRoms: (folderPath) => ipcRenderer.invoke('bridge:scanRoms', folderPath),
  launchGame: (options) => ipcRenderer.invoke('bridge:launchGame', options),
  killGame: () => ipcRenderer.invoke('bridge:killGame'),
  listControllers: () => ipcRenderer.invoke('bridge:listControllers'),
  saveMapping: (mapping) => ipcRenderer.invoke('bridge:saveMapping', mapping),
  scrapeGame: (game, ssUser, ssPassword) => ipcRenderer.invoke('bridge:scrapeGame', game, ssUser, ssPassword),
  createFolder:    (folderPath) => ipcRenderer.invoke('bridge:createFolder', folderPath),
  scanCollection:  (parentFolder) => ipcRenderer.invoke('bridge:scanCollection', parentFolder),
  moveFiles:      (filePaths, destFolder) => ipcRenderer.invoke('bridge:moveFiles', filePaths, destFolder),
  pickFiles:      () => ipcRenderer.invoke('bridge:pickFiles'),
  artworkExists: (game) => ipcRenderer.invoke('bridge:artworkExists', game),
  writeScrapeLog: (logText) => ipcRenderer.invoke('bridge:writeScrapeLog', logText),
  getArtworkPath: (game) => ipcRenderer.invoke('bridge:getArtworkPath', game),
  getMetadata:    (game) => ipcRenderer.invoke('bridge:getMetadata', game),
  saveArtwork:    (game, data) => ipcRenderer.invoke('bridge:saveArtwork', game, data),
  onProgress: (callback) => ipcRenderer.on('progress', (_e, data) => callback(data)),
  offProgress: (callback) => ipcRenderer.removeListener('progress', callback),
  ensureDolphinReady: () => ipcRenderer.invoke('bridge:ensureDolphinReady'),
  launchDolphinBare: () => ipcRenderer.invoke('bridge:launchDolphinBare'),
  // FIX_2026-06-07_DOLPHIN_DETECTION_RESTORE: pass controllerType through IPC
  launchDolphin: (romPath, controllerType) => ipcRenderer.invoke('bridge:launchDolphin', romPath, controllerType),
});
